


input_file: /data/share/DATA/PROC/ERA5/ERA5_3hourly_230101-250430.nc
output_file: /data/share/DATA/PROC/ERA5_ROMS_F/ROMS_F_ERA5_3hourly_221231-250430.nc
ref_time: days since 2000-1-1 00:00:00


dt: hourly


