

#input_file: /data/share/DATA/PROC/ERA5/ERA5_3hourly_230101-250430.nc
input_file: /home/shjo/DATA/ROMS_tmp.nc
output_file: /data/share/DATA/ROMS_INPUTS/tmp/ROMS_F_ERA5_3hourly_250401-250601.nc
ref_time: days since 2000-1-1 00:00:00


dt: hourly


