####################################################################################################
# Author: Youngmin Park                                                                            #
# Description: This script reads ROMS result files and extracts variables from the standard area.  #
#              The extracted variables are saved to a new NetCDF file.                             #
# Date: 2025-03-20                                                                                 #
####################################################################################################
RDomcfgPath : '/data/share/ROMS_NPZD/NWP15km/roms_grd_fennel_15km_smooth_v2.nc'
RomsRstHead : '/data/share/ROMS_NPZD/NWP15km_output/mon/'
RomsRstTail : 'NWP4_'
RomsNamlist : '/data/share/ROMS_NPZD/test/da_ocean_NWP4.in'
StdSaveHead : '/data/share/ROMS_NPZD/NWP15km_output/mon/'
OutputHead  : 'NIFS_NWP_Pre_'

Standard:
  latmin : 20.0
  latmax : 49.0
  lonmin : 115.0
  lonmax : 150.0
  hresol : 0.05  
  vdepth : [0, 10, 20, 30, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500]
  
ExtraVar:
 - temp : [rho, 3]
 - salt : [rho, 3]
 - u    : [u,   3]
 - v    : [v,   3]
 - NO3  : [rho, 3]
 - chlorophyll    : [rho, 3]
 - phytoplankton    : [rho, 3]
 - zooplankton    : [rho, 3]
 - zeta : [rho, 2]
  
nc_global_att:
  type : 'prediction model daily averages file'
  model_time_ref : 'UTC'
  created_by : 'National Institute of Fisheries Science'
