###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
#ininame : /mnt/c/Users/shjo9/Bridge/DATA/roms_ini.nc
#grdname : /mnt/c/Users/shjo9/Bridge/DATA/NWP4_grd_3_10m_LP.nc
ininame : /data/share/DATA/ROMS_INPUTS/ini/roms_ini_fennel_15km_v2_feb.nc
grdname : /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc

#weight_file: /mnt/c/USers/shjo9/Bridge/DATA/NWP4_weight_10m_LP.nc
weight_file: /data/share/DATA/ROMS_INPUTS/wght/NWP_weight_NWP4.nc
calc_weight: True

ncformat: NETCDF3_64BIT
force_write: True

bio_model_type: fennel

flood_method_for_ini: griddata #griddata / edt / linearND

ogcm_name: /data/share/DATA/RAW/00utc/HYCOM_20250201_00UTC.nc 

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

initdate            : 2025-02-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

vertical:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400




