###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
ininame: /mnt/c/Users/shjo9/Bridge/DATA/roms_ini.nc
grdname: /mnt/c/Users/shjo9/Bridge/DATA/NWP4_grd_3_10m_LP.nc

ogcm_name: /mnt/c/Users/shjo9/Bridge/DATA/HYCOM_20230101_00UTC.nc 

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

initdate            : 2023-01-01
time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : test - mk_ini
    clm_file        : test
    type            : test
    history         : test

vertical:
    layer_n         : 20
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400




