###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
bryname: /data/share/DATA/ROMS_INPUTS/bry/test_bry.nc
grdname: /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc
weight_file: /data/share/DATA/ROMS_INPUTS/wght/test_weight.nc
calc_weight: True

bio_model_type: npzd
flood_method_for_bry: edt

# 파일 -> 변수들 (순서 중요)
bio_ogcm_path:
  phyt_chl: [phyt, chl]
  zoo: [zoop]
  detr: [detr]

# 변수 이름 맵핑 (변환 필요할 경우)
bio_ogcm_var_name:
  longitude : lon
  latitude  : lat
  depth     : depth
  time      : time
  phyt      : phyc
  chl       : chl
  zoop      : zoop
  detr      : detr

bry_start_date: 2022-12-01 00:00:00
bry_end_date  : 2023-01-02 00:00:00
time_ref      : seconds since 2000-1-1 00:00:00

vertical:
  layer_n     : 36
  vtransform  : 2
  vstretching : 4
  theta_s     : 6.5
  theta_b     : 1
  tcline      : 400
